server {
    listen 80;
    server_name _;

    root /var/www/dummy-a;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Logs
    access_log /var/log/nginx/dummy-a-access.log;
    error_log  /var/log/nginx/dummy-a-error.log;
}
